apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: rag
  labels:
    app.kubernetes.io/name: ollama
spec:
  selector:
    app.kubernetes.io/name: ollama
  ports:
    - name: http
      port: 11434
      targetPort: 11434
